import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#004883",
        "surface-variant": "#31353e",
        "on-tertiary-fixed": "#2a1700",
        "surface-bright": "#353942",
        "inverse-surface": "#dfe2ee",
        "inverse-primary": "#0060ac",
        "secondary": "#4edea3",
        "on-primary-fixed": "#001c39",
        "surface-container-highest": "#31353e",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-on-surface": "#2c3039",
        "on-primary-container": "#003a6b",
        "background": "#0f131c",
        "surface-container-high": "#262a33",
        "error-container": "#93000a",
        "surface-dim": "#0f131c",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "on-surface": "#dfe2ee",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002113",
        "outline": "#8b919d",
        "primary-fixed-dim": "#a4c9ff",
        "on-surface-variant": "#c1c7d3",
        "on-secondary": "#003824",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#d4e3ff",
        "on-tertiary": "#472a00",
        "on-primary": "#00315d",
        "surface": "#0f131c",
        "on-background": "#dfe2ee",
        "surface-container": "#1c2028",
        "primary": "#a4c9ff",
        "surface-container-low": "#181c24",
        "error": "#ffb4ab",
        "outline-variant": "#414751",
        "tertiary-fixed": "#ffddb8",
        "tertiary-container": "#e29100",
        "surface-container-lowest": "#0a0e16",
        "tertiary": "#ffb95f",
        "on-tertiary-container": "#523200",
        "secondary-container": "#00a572",
        "surface-tint": "#a4c9ff",
        "primary-container": "#60a5fa"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
