import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#131b2e",
        "secondary-fixed": "#e1e0ff",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "primary": "#0058be",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f5fff6",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#fefcff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "surface-bright": "#faf8ff",
        "surface": "#faf8ff",
        "primary-container": "#2170e4",
        "on-secondary-fixed": "#07006c",
        "on-surface-variant": "#424754",
        "secondary-container": "#6063ee",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed-variant": "#004395",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed-variant": "#005236",
        "on-error-container": "#93000a",
        "tertiary": "#006947",
        "surface-container": "#eaedff",
        "outline-variant": "#c2c6d6",
        "on-tertiary-fixed": "#002113",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f3ff",
        "primary-fixed-dim": "#adc6ff",
        "background": "#faf8ff",
        "inverse-primary": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "tertiary-container": "#00855b",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#fffbff",
        "error-container": "#ffdad6",
        "outline": "#727785",
        "surface-tint": "#005ac2",
        "on-background": "#131b2e",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#283044",
        "secondary": "#4648d4",
        "primary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "0.75rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
