/**
 * PlacementOS — Deterministic Assessment Question Bank
 * 
 * Static, pre-filled questions for every supported engineering department.
 * Exactly 5 questions per department. No AI generation required.
 * These are loaded instantly when the candidate selects a department.
 */

import { AssessmentQuestion } from '@/types/team2-contract';

export type DepartmentCode = 'CSE' | 'EEE' | 'ECE' | 'Mechanical' | 'Civil' | 'Chemical' | 'Biotechnology';

// ─────────────────────────────────────────────
// EEE — Electrical and Electronics Engineering
// ─────────────────────────────────────────────
const EEE_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'eee-q1',
    skillId: 'ps-fault-analysis',
    skillName: 'Power Systems: Fault Analysis',
    subskill: 'Three-Phase Systems',
    difficulty: 'BASIC',
    questionText: 'In a balanced three-phase system, what is the phase difference between the three phase voltages?',
    options: [
      { id: 'eee-q1-a', text: '120 degrees' },
      { id: 'eee-q1-b', text: '90 degrees' },
      { id: 'eee-q1-c', text: '180 degrees' },
      { id: 'eee-q1-d', text: '60 degrees' },
    ],
    correctOptionId: 'eee-q1-a',
    explanation: 'In a balanced three-phase system, voltages are equal in magnitude and displaced by 120° from each other, forming a symmetrical set.',
  },
  {
    id: 'eee-q2',
    skillId: 'ps-fault-analysis',
    skillName: 'Power Systems: Transformers',
    subskill: 'Transformer Principles',
    difficulty: 'BASIC',
    questionText: 'What is the primary purpose of a transformer in a power system?',
    options: [
      { id: 'eee-q2-a', text: 'To convert AC to DC' },
      { id: 'eee-q2-b', text: 'To step up or step down voltage levels' },
      { id: 'eee-q2-c', text: 'To store electrical energy' },
      { id: 'eee-q2-d', text: 'To generate reactive power' },
    ],
    correctOptionId: 'eee-q2-b',
    explanation: 'Transformers operate on mutual induction to transfer electrical energy between circuits while changing voltage levels, enabling efficient long-distance power transmission.',
  },
  {
    id: 'eee-q3',
    skillId: 'ps-fault-analysis',
    skillName: 'Power Systems: Machines',
    subskill: 'Induction Motors',
    difficulty: 'INTERMEDIATE',
    questionText: 'What happens to the synchronous speed of an induction motor when the supply frequency increases?',
    options: [
      { id: 'eee-q3-a', text: 'Synchronous speed decreases' },
      { id: 'eee-q3-b', text: 'Synchronous speed remains unchanged' },
      { id: 'eee-q3-c', text: 'Synchronous speed increases proportionally' },
      { id: 'eee-q3-d', text: 'The motor stalls immediately' },
    ],
    correctOptionId: 'eee-q3-c',
    explanation: 'Synchronous speed Ns = 120f/P. Since speed is directly proportional to frequency f, increasing supply frequency proportionally increases the synchronous speed.',
  },
  {
    id: 'eee-q4',
    skillId: 'ps-relay-protection',
    skillName: 'Power Systems: Protection',
    subskill: 'Protective Relays',
    difficulty: 'INTERMEDIATE',
    questionText: 'What is the primary purpose of protective relays in a power system?',
    options: [
      { id: 'eee-q4-a', text: 'To regulate voltage levels across the network' },
      { id: 'eee-q4-b', text: 'To detect abnormal conditions and isolate faulted sections' },
      { id: 'eee-q4-c', text: 'To improve the power factor of the system' },
      { id: 'eee-q4-d', text: 'To reduce harmonic distortion in the supply' },
    ],
    correctOptionId: 'eee-q4-b',
    explanation: 'Protective relays continuously monitor system parameters (current, voltage, frequency) and initiate circuit breaker tripping to isolate faulted sections, preventing equipment damage and system instability.',
  },
  {
    id: 'eee-q5',
    skillId: 'ps-fault-analysis',
    skillName: 'Power Systems: Fault Analysis',
    subskill: 'Sequence Components',
    difficulty: 'ADVANCED',
    questionText: 'What is zero-sequence current primarily associated with in an unbalanced fault?',
    options: [
      { id: 'eee-q5-a', text: 'Positive phase rotation of currents' },
      { id: 'eee-q5-b', text: 'Equal and in-phase currents in all three phases flowing through the neutral/ground path' },
      { id: 'eee-q5-c', text: 'Negative phase rotation indicating reverse power flow' },
      { id: 'eee-q5-d', text: 'Harmonic currents generated by nonlinear loads' },
    ],
    correctOptionId: 'eee-q5-b',
    explanation: 'Zero-sequence currents are equal in magnitude and in-phase across all three phases. They can only flow when a neutral/ground return path exists, making them critical indicators of ground faults.',
  },
];

// ─────────────────────────────────────────────
// CSE — Computer Science and Engineering
// ─────────────────────────────────────────────
const CSE_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'cse-q1',
    skillId: 'fs-distributed',
    skillName: 'Data Structures & Algorithms',
    subskill: 'Time Complexity',
    difficulty: 'BASIC',
    questionText: 'What is the average-case time complexity of binary search on a sorted array of n elements?',
    options: [
      { id: 'cse-q1-a', text: 'O(n)' },
      { id: 'cse-q1-b', text: 'O(log n)' },
      { id: 'cse-q1-c', text: 'O(n log n)' },
      { id: 'cse-q1-d', text: 'O(1)' },
    ],
    correctOptionId: 'cse-q1-b',
    explanation: 'Binary search halves the search space with each comparison, resulting in O(log n) comparisons in the average and worst cases.',
  },
  {
    id: 'cse-q2',
    skillId: 'fs-distributed',
    skillName: 'Operating Systems',
    subskill: 'Process Management',
    difficulty: 'INTERMEDIATE',
    questionText: 'Which condition is NOT required for a deadlock to occur according to Coffman\'s conditions?',
    options: [
      { id: 'cse-q2-a', text: 'Mutual Exclusion' },
      { id: 'cse-q2-b', text: 'Hold and Wait' },
      { id: 'cse-q2-c', text: 'Preemption' },
      { id: 'cse-q2-d', text: 'Circular Wait' },
    ],
    correctOptionId: 'cse-q2-c',
    explanation: 'The four Coffman conditions are: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. Preemption (the ability to forcibly take resources) actually PREVENTS deadlock; its absence (No Preemption) is required.',
  },
  {
    id: 'cse-q3',
    skillId: 'fs-distributed',
    skillName: 'Database Systems',
    subskill: 'Normalization',
    difficulty: 'INTERMEDIATE',
    questionText: 'A relation is in Third Normal Form (3NF) if it satisfies which of the following conditions?',
    options: [
      { id: 'cse-q3-a', text: 'It is in 2NF and has no transitive dependencies on the primary key' },
      { id: 'cse-q3-b', text: 'All attributes are functionally dependent on the primary key' },
      { id: 'cse-q3-c', text: 'It has no repeating groups and all attributes are atomic' },
      { id: 'cse-q3-d', text: 'Every determinant is a candidate key (BCNF condition)' },
    ],
    correctOptionId: 'cse-q3-a',
    explanation: '3NF requires the relation to be in 2NF (no partial dependencies) and additionally eliminates transitive dependencies — no non-prime attribute should depend on another non-prime attribute.',
  },
  {
    id: 'cse-q4',
    skillId: 'fs-distributed',
    skillName: 'Computer Networks',
    subskill: 'TCP/IP',
    difficulty: 'INTERMEDIATE',
    questionText: 'In the TCP three-way handshake, what is the correct sequence of segments exchanged?',
    options: [
      { id: 'cse-q4-a', text: 'SYN → SYN-ACK → ACK' },
      { id: 'cse-q4-b', text: 'ACK → SYN → SYN-ACK' },
      { id: 'cse-q4-c', text: 'SYN → ACK → SYN-ACK' },
      { id: 'cse-q4-d', text: 'FIN → SYN-ACK → ACK' },
    ],
    correctOptionId: 'cse-q4-a',
    explanation: 'TCP connection establishment: Client sends SYN, server responds with SYN-ACK, client confirms with ACK. This three-way handshake ensures both sides agree on initial sequence numbers.',
  },
  {
    id: 'cse-q5',
    skillId: 'fs-distributed',
    skillName: 'System Design',
    subskill: 'Distributed Systems',
    difficulty: 'ADVANCED',
    questionText: 'According to the CAP theorem, a distributed system can guarantee at most how many of the three properties (Consistency, Availability, Partition Tolerance) simultaneously?',
    options: [
      { id: 'cse-q5-a', text: 'All three simultaneously' },
      { id: 'cse-q5-b', text: 'Any two out of three' },
      { id: 'cse-q5-c', text: 'Only one at a time' },
      { id: 'cse-q5-d', text: 'None — trade-offs are always unavoidable' },
    ],
    correctOptionId: 'cse-q5-b',
    explanation: 'The CAP theorem (Brewer\'s theorem) proves that in the presence of a network partition, a distributed system must choose between consistency and availability. At most two of the three guarantees can be met simultaneously.',
  },
];

// ─────────────────────────────────────────────
// ECE — Electronics and Communication Engineering
// ─────────────────────────────────────────────
const ECE_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'ece-q1',
    skillId: 'emb-rtos',
    skillName: 'Digital Electronics',
    subskill: 'Logic Gates',
    difficulty: 'BASIC',
    questionText: 'What is the output of an XOR gate when both inputs are logic HIGH (1)?',
    options: [
      { id: 'ece-q1-a', text: '1' },
      { id: 'ece-q1-b', text: '0' },
      { id: 'ece-q1-c', text: 'Undefined' },
      { id: 'ece-q1-d', text: 'High impedance' },
    ],
    correctOptionId: 'ece-q1-b',
    explanation: 'XOR (Exclusive OR) outputs 1 only when inputs differ. When both inputs are 1, the output is 0. XOR truth table: 0⊕0=0, 0⊕1=1, 1⊕0=1, 1⊕1=0.',
  },
  {
    id: 'ece-q2',
    skillId: 'emb-rtos',
    skillName: 'Signal Processing',
    subskill: 'Sampling Theory',
    difficulty: 'INTERMEDIATE',
    questionText: 'According to the Nyquist-Shannon sampling theorem, what is the minimum sampling frequency required to accurately reconstruct a signal with maximum frequency component of 4 kHz?',
    options: [
      { id: 'ece-q2-a', text: '4 kHz' },
      { id: 'ece-q2-b', text: '8 kHz' },
      { id: 'ece-q2-c', text: '16 kHz' },
      { id: 'ece-q2-d', text: '2 kHz' },
    ],
    correctOptionId: 'ece-q2-b',
    explanation: 'Nyquist theorem states the sampling frequency must be at least twice the maximum signal frequency: fs ≥ 2·fmax = 2 × 4 kHz = 8 kHz to avoid aliasing.',
  },
  {
    id: 'ece-q3',
    skillId: 'emb-rtos',
    skillName: 'Communication Systems',
    subskill: 'Modulation',
    difficulty: 'INTERMEDIATE',
    questionText: 'In Frequency Modulation (FM), what parameter of the carrier wave is varied in proportion to the message signal?',
    options: [
      { id: 'ece-q3-a', text: 'Amplitude' },
      { id: 'ece-q3-b', text: 'Phase' },
      { id: 'ece-q3-c', text: 'Frequency' },
      { id: 'ece-q3-d', text: 'Wavelength and amplitude simultaneously' },
    ],
    correctOptionId: 'ece-q3-c',
    explanation: 'In FM, the instantaneous frequency of the carrier deviates from the center frequency proportionally to the amplitude of the modulating signal, while carrier amplitude remains constant.',
  },
  {
    id: 'ece-q4',
    skillId: 'emb-rtos',
    skillName: 'Embedded Systems',
    subskill: 'Microcontrollers',
    difficulty: 'INTERMEDIATE',
    questionText: 'What is the primary advantage of using Direct Memory Access (DMA) over programmed I/O in embedded systems?',
    options: [
      { id: 'ece-q4-a', text: 'DMA uses less physical memory' },
      { id: 'ece-q4-b', text: 'DMA allows data transfer without CPU intervention, freeing the CPU for other tasks' },
      { id: 'ece-q4-c', text: 'DMA increases clock speed of the processor' },
      { id: 'ece-q4-d', text: 'DMA eliminates the need for interrupt controllers' },
    ],
    correctOptionId: 'ece-q4-b',
    explanation: 'DMA enables peripherals to transfer data directly to/from memory without CPU involvement in each byte transfer, significantly improving throughput and allowing the CPU to execute other instructions concurrently.',
  },
  {
    id: 'ece-q5',
    skillId: 'emb-rtos',
    skillName: 'VLSI Design',
    subskill: 'CMOS Technology',
    difficulty: 'ADVANCED',
    questionText: 'In a CMOS inverter, what is the static power dissipation when the output is in a stable logic state?',
    options: [
      { id: 'ece-q5-a', text: 'Equal to VDD × IDD' },
      { id: 'ece-q5-b', text: 'Ideally zero (only leakage current flows)' },
      { id: 'ece-q5-c', text: 'Half of the dynamic power dissipation' },
      { id: 'ece-q5-d', text: 'Proportional to the switching frequency' },
    ],
    correctOptionId: 'ece-q5-b',
    explanation: 'In a stable state, one MOSFET in the CMOS pair is OFF, creating no direct path from VDD to ground. Static power dissipation is ideally zero, with only sub-threshold leakage current contributing a negligible amount.',
  },
];

// ─────────────────────────────────────────────
// MECH — Mechanical Engineering
// ─────────────────────────────────────────────
const MECH_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'mech-q1',
    skillId: 'ctrl-state-space',
    skillName: 'Thermodynamics',
    subskill: 'Laws of Thermodynamics',
    difficulty: 'BASIC',
    questionText: 'According to the Second Law of Thermodynamics, what is impossible in a cyclic process?',
    options: [
      { id: 'mech-q1-a', text: 'Converting work entirely into heat' },
      { id: 'mech-q1-b', text: 'Converting heat entirely into work without any other effect' },
      { id: 'mech-q1-c', text: 'Transferring heat from a hot body to a cold body' },
      { id: 'mech-q1-d', text: 'Having a system with zero entropy' },
    ],
    correctOptionId: 'mech-q1-b',
    explanation: 'The Kelvin-Planck statement of the Second Law: It is impossible to construct a heat engine that operates in a cycle and converts ALL heat from a single reservoir into work with no other effect. Some heat must always be rejected.',
  },
  {
    id: 'mech-q2',
    skillId: 'ctrl-state-space',
    skillName: 'Strength of Materials',
    subskill: 'Stress Analysis',
    difficulty: 'INTERMEDIATE',
    questionText: 'What does the yield strength of a material represent?',
    options: [
      { id: 'mech-q2-a', text: 'The maximum stress a material can withstand before fracture' },
      { id: 'mech-q2-b', text: 'The stress at which a material begins permanent (plastic) deformation' },
      { id: 'mech-q2-c', text: 'The stress at which strain hardening begins' },
      { id: 'mech-q2-d', text: 'The fatigue limit under cyclic loading' },
    ],
    correctOptionId: 'mech-q2-b',
    explanation: 'Yield strength marks the transition from elastic to plastic behavior. Below this stress, the material returns to its original shape; above it, permanent deformation occurs.',
  },
  {
    id: 'mech-q3',
    skillId: 'ctrl-state-space',
    skillName: 'Manufacturing',
    subskill: 'Machining Processes',
    difficulty: 'INTERMEDIATE',
    questionText: 'In CNC machining, what does the G-code command G00 instruct the machine to do?',
    options: [
      { id: 'mech-q3-a', text: 'Linear interpolation at feed rate' },
      { id: 'mech-q3-b', text: 'Rapid positioning (non-cutting traverse)' },
      { id: 'mech-q3-c', text: 'Circular interpolation clockwise' },
      { id: 'mech-q3-d', text: 'Tool change command' },
    ],
    correctOptionId: 'mech-q3-b',
    explanation: 'G00 commands the CNC machine to move to the specified coordinates at maximum traversal speed without cutting. It is used for rapid positioning between machining operations.',
  },
  {
    id: 'mech-q4',
    skillId: 'ctrl-state-space',
    skillName: 'Fluid Mechanics',
    subskill: 'Flow Dynamics',
    difficulty: 'INTERMEDIATE',
    questionText: 'What does a Reynolds number greater than 4000 in pipe flow typically indicate?',
    options: [
      { id: 'mech-q4-a', text: 'Laminar flow with predictable streamlines' },
      { id: 'mech-q4-b', text: 'Transitional flow between laminar and turbulent' },
      { id: 'mech-q4-c', text: 'Fully developed turbulent flow' },
      { id: 'mech-q4-d', text: 'Supersonic compressible flow' },
    ],
    correctOptionId: 'mech-q4-c',
    explanation: 'In pipe flow, Re < 2300 indicates laminar flow, 2300 < Re < 4000 is transitional, and Re > 4000 indicates fully turbulent flow with chaotic velocity fluctuations and enhanced mixing.',
  },
  {
    id: 'mech-q5',
    skillId: 'ctrl-state-space',
    skillName: 'Machine Design',
    subskill: 'Fatigue Analysis',
    difficulty: 'ADVANCED',
    questionText: 'In the S-N curve (Wöhler curve) for ferrous metals, what does the endurance limit represent?',
    options: [
      { id: 'mech-q5-a', text: 'The maximum stress amplitude below which the material can endure an infinite number of load cycles without fatigue failure' },
      { id: 'mech-q5-b', text: 'The stress at which the material fails after exactly 10^6 cycles' },
      { id: 'mech-q5-c', text: 'The ultimate tensile strength divided by the safety factor' },
      { id: 'mech-q5-d', text: 'The creep rupture stress at elevated temperatures' },
    ],
    correctOptionId: 'mech-q5-a',
    explanation: 'The endurance limit (fatigue limit) for ferrous metals is the stress amplitude below which the material theoretically sustains an infinite number of cycles. This asymptotic behavior is characteristic of steels and cast irons.',
  },
];

// ─────────────────────────────────────────────
// CIVIL — Civil Engineering
// ─────────────────────────────────────────────
const CIVIL_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'civil-q1',
    skillId: 'civ-fea',
    skillName: 'Structural Engineering',
    subskill: 'Beam Analysis',
    difficulty: 'BASIC',
    questionText: 'What type of support provides both vertical and horizontal reactions but no moment restraint?',
    options: [
      { id: 'civil-q1-a', text: 'Fixed support' },
      { id: 'civil-q1-b', text: 'Pinned (hinged) support' },
      { id: 'civil-q1-c', text: 'Roller support' },
      { id: 'civil-q1-d', text: 'Free end' },
    ],
    correctOptionId: 'civil-q1-b',
    explanation: 'A pinned support restrains translation in both x and y directions (providing two reaction forces) but allows rotation, hence provides no moment reaction.',
  },
  {
    id: 'civil-q2',
    skillId: 'civ-fea',
    skillName: 'Geotechnical Engineering',
    subskill: 'Soil Mechanics',
    difficulty: 'INTERMEDIATE',
    questionText: 'In Terzaghi\'s consolidation theory, what does the coefficient of consolidation (Cv) primarily govern?',
    options: [
      { id: 'civil-q2-a', text: 'The ultimate magnitude of settlement' },
      { id: 'civil-q2-b', text: 'The rate at which excess pore water pressure dissipates over time' },
      { id: 'civil-q2-c', text: 'The shear strength of the consolidated clay' },
      { id: 'civil-q2-d', text: 'The angle of internal friction of the soil' },
    ],
    correctOptionId: 'civil-q2-b',
    explanation: 'Cv determines the TIME RATE of consolidation — how quickly excess pore water pressure dissipates and settlement occurs. Higher Cv means faster consolidation, not greater total settlement.',
  },
  {
    id: 'civil-q3',
    skillId: 'civ-fea',
    skillName: 'Construction Management',
    subskill: 'Concrete Technology',
    difficulty: 'INTERMEDIATE',
    questionText: 'What is the standard curing period recommended for ordinary Portland cement concrete to achieve its design strength?',
    options: [
      { id: 'civil-q3-a', text: '3 days' },
      { id: 'civil-q3-b', text: '7 days' },
      { id: 'civil-q3-c', text: '28 days' },
      { id: 'civil-q3-d', text: '56 days' },
    ],
    correctOptionId: 'civil-q3-c',
    explanation: 'OPC concrete achieves approximately 99% of its design (characteristic) compressive strength at 28 days of moist curing. This is the standard reference period for strength testing per IS 456 and most international codes.',
  },
  {
    id: 'civil-q4',
    skillId: 'civ-fea',
    skillName: 'Transportation Engineering',
    subskill: 'Highway Design',
    difficulty: 'INTERMEDIATE',
    questionText: 'What is the primary purpose of providing superelevation on a highway curve?',
    options: [
      { id: 'civil-q4-a', text: 'To improve visibility around the curve' },
      { id: 'civil-q4-b', text: 'To counteract centrifugal force and prevent vehicles from skidding outward' },
      { id: 'civil-q4-c', text: 'To drain rainwater from the road surface' },
      { id: 'civil-q4-d', text: 'To reduce the pavement thickness on curves' },
    ],
    correctOptionId: 'civil-q4-b',
    explanation: 'Superelevation tilts the road surface inward on curves so that a component of the vehicle\'s weight counterbalances centrifugal force, reducing the tendency to skid outward.',
  },
  {
    id: 'civil-q5',
    skillId: 'civ-fea',
    skillName: 'Structural Engineering',
    subskill: 'Seismic Design',
    difficulty: 'ADVANCED',
    questionText: 'In earthquake-resistant design, what does the response reduction factor (R) account for in the seismic base shear calculation?',
    options: [
      { id: 'civil-q5-a', text: 'The amplification of ground motion at the site' },
      { id: 'civil-q5-b', text: 'The inherent overstrength and ductility of the structural system to absorb and dissipate seismic energy' },
      { id: 'civil-q5-c', text: 'The weight of non-structural elements in the building' },
      { id: 'civil-q5-d', text: 'The soil-structure interaction effect' },
    ],
    correctOptionId: 'civil-q5-b',
    explanation: 'The response reduction factor R permits designing for reduced seismic forces because ductile structural systems can undergo inelastic deformation and dissipate energy without collapse. Higher R values apply to more ductile systems.',
  },
];

// ─────────────────────────────────────────────
// Chemical Engineering
// ─────────────────────────────────────────────
const CHEMICAL_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'chem-q1',
    skillId: 'proc-scada',
    skillName: 'Process Engineering',
    subskill: 'Mass Balance',
    difficulty: 'BASIC',
    questionText: 'In a steady-state continuous process with no accumulation, what fundamental law governs the material balance?',
    options: [
      { id: 'chem-q1-a', text: 'Conservation of mass: Input = Output + Generation - Consumption' },
      { id: 'chem-q1-b', text: 'Ideal gas law: PV = nRT' },
      { id: 'chem-q1-c', text: 'Newton\'s second law of motion' },
      { id: 'chem-q1-d', text: 'Fourier\'s law of heat conduction' },
    ],
    correctOptionId: 'chem-q1-a',
    explanation: 'At steady state with no accumulation, the mass balance reduces to: Mass In + Mass Generated = Mass Out + Mass Consumed. For non-reacting systems, this simplifies to Mass In = Mass Out.',
  },
  {
    id: 'chem-q2',
    skillId: 'proc-scada',
    skillName: 'Reaction Engineering',
    subskill: 'Reactor Design',
    difficulty: 'INTERMEDIATE',
    questionText: 'For a first-order irreversible reaction A → B, what is the relationship between conversion and reactor volume in a CSTR?',
    options: [
      { id: 'chem-q2-a', text: 'Volume is proportional to ln(1/(1-X))' },
      { id: 'chem-q2-b', text: 'Volume is proportional to X/(1-X)' },
      { id: 'chem-q2-c', text: 'Volume is independent of conversion' },
      { id: 'chem-q2-d', text: 'Volume is proportional to X²' },
    ],
    correctOptionId: 'chem-q2-b',
    explanation: 'For a first-order reaction in a CSTR: τ = X/(k(1-X)), so V = FA0·X/(k·CA0·(1-X)). The volume-conversion relationship follows X/(1-X). Note: ln(1/(1-X)) applies to a PFR.',
  },
  {
    id: 'chem-q3',
    skillId: 'proc-scada',
    skillName: 'Heat Transfer',
    subskill: 'Heat Exchangers',
    difficulty: 'INTERMEDIATE',
    questionText: 'In a shell-and-tube heat exchanger, what is the primary advantage of counter-current flow over co-current (parallel) flow?',
    options: [
      { id: 'chem-q3-a', text: 'Lower pressure drop across the exchanger' },
      { id: 'chem-q3-b', text: 'Higher mean temperature difference, resulting in more efficient heat transfer' },
      { id: 'chem-q3-c', text: 'Simpler mechanical construction' },
      { id: 'chem-q3-d', text: 'Elimination of fouling on tube surfaces' },
    ],
    correctOptionId: 'chem-q3-b',
    explanation: 'Counter-current flow maintains a more uniform and higher log-mean temperature difference (LMTD) across the exchanger length compared to co-current flow, enabling greater heat duty for the same surface area.',
  },
  {
    id: 'chem-q4',
    skillId: 'proc-scada',
    skillName: 'Process Control',
    subskill: 'PID Control',
    difficulty: 'INTERMEDIATE',
    questionText: 'In a PID controller, what does the integral (I) action primarily address?',
    options: [
      { id: 'chem-q4-a', text: 'Rapid response to sudden disturbances' },
      { id: 'chem-q4-b', text: 'Elimination of steady-state offset (error)' },
      { id: 'chem-q4-c', text: 'Prediction of future error trends' },
      { id: 'chem-q4-d', text: 'Reduction of oscillation amplitude' },
    ],
    correctOptionId: 'chem-q4-b',
    explanation: 'The integral action accumulates past errors over time and drives the controller output until the steady-state error is zero. This eliminates the offset that pure proportional (P) control cannot remove.',
  },
  {
    id: 'chem-q5',
    skillId: 'proc-scada',
    skillName: 'Separation Processes',
    subskill: 'Distillation',
    difficulty: 'ADVANCED',
    questionText: 'In McCabe-Thiele graphical method for binary distillation, what does the intersection of the operating lines (rectifying and stripping) on the y-x diagram represent?',
    options: [
      { id: 'chem-q5-a', text: 'The azeotropic composition of the mixture' },
      { id: 'chem-q5-b', text: 'The feed stage composition and thermal condition (q-line intersection)' },
      { id: 'chem-q5-c', text: 'The maximum possible purity of the distillate' },
      { id: 'chem-q5-d', text: 'The reboiler duty required for separation' },
    ],
    correctOptionId: 'chem-q5-b',
    explanation: 'The rectifying and stripping operating lines intersect on the q-line (feed line). This intersection point determines the feed tray location and is governed by the feed composition (zF) and thermal condition (q parameter).',
  },
];

// ─────────────────────────────────────────────
// Biotechnology
// ─────────────────────────────────────────────
const BIOTECH_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'bio-q1',
    skillId: 'bio-fermentation',
    skillName: 'Molecular Biology',
    subskill: 'PCR Techniques',
    difficulty: 'BASIC',
    questionText: 'What is the purpose of the denaturation step in Polymerase Chain Reaction (PCR)?',
    options: [
      { id: 'bio-q1-a', text: 'To allow primers to bind to the template DNA' },
      { id: 'bio-q1-b', text: 'To separate the double-stranded DNA into single strands by heating' },
      { id: 'bio-q1-c', text: 'To activate the DNA polymerase enzyme' },
      { id: 'bio-q1-d', text: 'To synthesize new complementary DNA strands' },
    ],
    correctOptionId: 'bio-q1-b',
    explanation: 'Denaturation (typically at 94-98°C) breaks the hydrogen bonds between complementary bases, separating double-stranded DNA into two single strands that serve as templates for primer annealing.',
  },
  {
    id: 'bio-q2',
    skillId: 'bio-fermentation',
    skillName: 'Bioprocess Engineering',
    subskill: 'Fermentation',
    difficulty: 'INTERMEDIATE',
    questionText: 'In a batch fermentation, during which growth phase does the specific growth rate (μ) equal the maximum specific growth rate (μmax)?',
    options: [
      { id: 'bio-q2-a', text: 'Lag phase' },
      { id: 'bio-q2-b', text: 'Exponential (log) phase' },
      { id: 'bio-q2-c', text: 'Stationary phase' },
      { id: 'bio-q2-d', text: 'Death phase' },
    ],
    correctOptionId: 'bio-q2-b',
    explanation: 'During the exponential phase, nutrients are abundant and cells multiply at their maximum rate. The specific growth rate μ equals μmax, and cell concentration increases exponentially: X = X0 · e^(μmax·t).',
  },
  {
    id: 'bio-q3',
    skillId: 'bio-fermentation',
    skillName: 'Genetic Engineering',
    subskill: 'Cloning Vectors',
    difficulty: 'INTERMEDIATE',
    questionText: 'What is the essential feature a plasmid must possess to function as a cloning vector?',
    options: [
      { id: 'bio-q3-a', text: 'Large size exceeding 100 kb for inserting multiple genes' },
      { id: 'bio-q3-b', text: 'An origin of replication (ori), a selectable marker, and a multiple cloning site' },
      { id: 'bio-q3-c', text: 'Integration capability into the host chromosome' },
      { id: 'bio-q3-d', text: 'Self-transmissibility between bacterial cells' },
    ],
    correctOptionId: 'bio-q3-b',
    explanation: 'A functional cloning vector needs: (1) ori for autonomous replication, (2) selectable marker (e.g., antibiotic resistance) to identify transformed cells, and (3) MCS with unique restriction sites for inserting foreign DNA.',
  },
  {
    id: 'bio-q4',
    skillId: 'bio-fermentation',
    skillName: 'Downstream Processing',
    subskill: 'Chromatography',
    difficulty: 'INTERMEDIATE',
    questionText: 'In protein purification, what property does ion-exchange chromatography exploit to separate proteins?',
    options: [
      { id: 'bio-q4-a', text: 'Molecular weight differences' },
      { id: 'bio-q4-b', text: 'Net surface charge of proteins at a given pH' },
      { id: 'bio-q4-c', text: 'Hydrophobic surface patches on the protein' },
      { id: 'bio-q4-d', text: 'Specific ligand-binding affinity' },
    ],
    correctOptionId: 'bio-q4-b',
    explanation: 'Ion-exchange chromatography separates proteins based on their net charge. Cation exchangers bind positively charged proteins, anion exchangers bind negatively charged proteins. Elution is achieved by increasing salt concentration or changing pH.',
  },
  {
    id: 'bio-q5',
    skillId: 'bio-fermentation',
    skillName: 'Bioreactor Design',
    subskill: 'Scale-Up',
    difficulty: 'ADVANCED',
    questionText: 'When scaling up a stirred-tank bioreactor from lab to production scale, which parameter is most commonly kept constant to maintain similar oxygen transfer rates?',
    options: [
      { id: 'bio-q5-a', text: 'Impeller tip speed' },
      { id: 'bio-q5-b', text: 'Volumetric oxygen transfer coefficient (kLa)' },
      { id: 'bio-q5-c', text: 'Impeller Reynolds number' },
      { id: 'bio-q5-d', text: 'Power input per unit volume (P/V)' },
    ],
    correctOptionId: 'bio-q5-b',
    explanation: 'Maintaining constant kLa ensures that the oxygen transfer rate (OTR = kLa × (C* - CL)) is preserved at larger scale. This is critical because aerobic cultures are often oxygen-transfer-limited. P/V is often used as a correlating parameter.',
  },
];

// ─────────────────────────────────────────────
// Master Question Bank Mapping
// ─────────────────────────────────────────────
export const DEPARTMENT_QUESTION_BANK: Record<DepartmentCode, AssessmentQuestion[]> = {
  CSE: CSE_QUESTIONS,
  EEE: EEE_QUESTIONS,
  ECE: ECE_QUESTIONS,
  Mechanical: MECH_QUESTIONS,
  Civil: CIVIL_QUESTIONS,
  Chemical: CHEMICAL_QUESTIONS,
  Biotechnology: BIOTECH_QUESTIONS,
};

/**
 * Returns exactly 5 deterministic, pre-filled questions for the given department.
 * No AI generation. No network calls. Instant.
 */
export function getQuestionsForDepartment(department: DepartmentCode): AssessmentQuestion[] {
  return DEPARTMENT_QUESTION_BANK[department] || EEE_QUESTIONS;
}
